### ISSUE TITLE
container should fail if rclone fails

### ISSUE THREAD

**Issue by beohof** [Mumie-hub/docker-services#14]
Hi :),

first things first: nice work! 

I'd suggest the container should fail if rclone returns state 1 for the mount e.g. when there is no correct config file supplied. I might get into that myself and do a pull request if you wish.

Thanks again for the nice work and a nice weekend.

**Comment by Mumie-hub** [comment]
hi, of course, feel free to make a pull request :). Maybe we could use some init system like [/tini](https://github.com/krallin/tini).

**Comment by bennithekid** [comment]
Hi :),
tini is now integrated in docker but is no use in your originating code because of a always true loop which restarts rclone if failed. I remove it in Pull #16. Now the behavior might be managed by "--init" (tini) or by docker compose. I consider this issue closed.

**Comment by bennithekid** [comment]
Oh sorry, made my push request to the master branch. Please deny this. I'll pull the dev branch next time.

**Comment by Mumie-hub** [comment]
the container should fail now, if rclone exits, crashes etc.
