### ISSUE TITLE
Show Output of rclone mount command

### ISSUE THREAD

**Issue by cron410** [Mumie-hub/docker-services#21]
I'm not overly proficient with bash and I can't find a way to redirect the stdout of the rclone mount command in your start.sh script so users can see errors and any other output of the command. I tried redirecting stderr to stdout with `2>&1` which did not work. Below is the kind of errors I am trying to show in docker logs.

I ran these commands inside the container to find my error. (didn't add a colon to the remote)
```
/ # /usr/sbin/rclone --config $ConfigPath mount $RemotePath $MountPoint $MountCommands & wait ${!}
Error: unknown command "gcache" for "rclone"
Run 'rclone --help' for usage.
2018/07/26 19:35:26 Fatal error: unknown command "gcache" for "rclone"
[1]+  Done(1)                    /usr/sbin/rclone --config ${ConfigPath} mount ${RemotePath} ${MountPoint} ${MountCommands}
/ # echo "/usr/sbin/rclone --config $ConfigPath mount $RemotePath $MountPoint $MountCommands & wait ${!}"
/usr/sbin/rclone --config  mount gcache /data --allow-other --allow-non-empty --dir-cache-time=160h --cache-chunk-size=10M --cache-info-age=168h --cache-workers=5 --buffer-size=500M --attr-timeout=1s & wait 31
/ # exit
```

I only see this in `docker logs rclone`
```
==================================================
Mounting gcache: to /data at: 2018.07.26-19:37:02
sending SIGTERM to child pid
Unmounting: fusermount -u -z /data at: 2018.07.26-19:52:09
exiting container now
```

**Comment by Mumie-hub** [comment]
hi, sorry for my late reply.
Are you starting your container with -it?

**Comment by Mumie-hub** [comment]
hi, sorry for the late reply.
you still have the problem? My output is working fine.

**Comment by cron410** [comment]
I think i was hoping for more verbose output on error instead of `sending SIGTERM to child pid` and `Unmounting: fusermount`. My run command was misformed and I was trying to find my typo. That's all been sorted out, but I think for new users, it would help to show what the docker run command pieces together from the user's input to form the final `rclone mount` command.

**Comment by Mumie-hub** [comment]
A debug option has been added
