### ISSUE TITLE
Cannot enter console

### ISSUE THREAD

**Issue by mattmac24** [Mumie-hub/docker-services#22]
Hi,

When trying to enter the console in Portainer I get the following error:

`OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown`

It would make troubleshooting issues easier if this was possible.

Thanks

**Comment by Mumie-hub** [comment]
hi @mattmac24,

alpine Linux does not use bash shell.
You have to select /bin/sh in portainer console.
![portainer](https://user-images.githubusercontent.com/16039039/45925640-b2d21480-bf19-11e8-8e3a-21a837d7df8f.JPG)

Best Regards

**Comment by mattmac24** [comment]
Thanks for the tip!
