### ISSUE TITLE
Empty mount on host

### ISSUE THREAD

**Issue by nevrion** [Mumie-hub/docker-services#28]
hi, I have the following problem ... no matter how many times and on which system I try, on the host rclone is not mounted ... in the container it works. Where's the problem? I am slowly despairing.

**Comment by Mumie-hub** [comment]
hi @nevrion, I guess you are missing the mendatory :shared command at the end of the volume -v /host/mount/point:/inside/container:shared

**Comment by nevrion** [comment]
thank you :)

**Comment by bonny1992** [comment]
Mmh...
Sorry to dig up this old issue but I have the same problem.

I am on DSM 5 and I'm encountering the same "empty" mount on host, but working inside the container.

Here's my docker run command:
`docker run -d --name rclone-mount \
    --cap-add SYS_ADMIN \
    --device /dev/fuse \
    --security-opt apparmor:unconfined \
    -e RemotePath="gdrive_unlimited:" \
    -e MountCommands="--allow-other --allow-non-empty --dir-cache-time 672h --vfs-cache-max-age 675h --vfs-read-chunk-size 128M --vfs-read-chunk-size-limit 1G --buffer-size 32M" \
    -e ConfigName="rclone.conf" \
    -v /volume1/Storage/rclone/config:/config \
    -v /volume1/Storage/gdrive_mount:/mnt/mediaefs:shared \
mumiehub/rclone-mount`

Of course if I enter the container using docker exec and cding to the /mnt/mediaefs it works.

Can you help me?

**Comment by thomas-bc** [comment]
Digging this up once more cause I had a lot of troubles finding this piece of documentation, and maybe it can help:
https://docs.docker.com/storage/bind-mounts/#configure-bind-propagation

The `:shared` part of the volume seems to only be configurable on Linux which caused some headaches since I'm not developing on a Linux machine...

**Comment by bonny1992** [comment]
Well, it's not pure but DSM is still Linux.

Maybe it has something with the version not being updated...

**Comment by thomas-bc** [comment]
Sorry I didn't express myself correctly.
If the command you linked ran correctly, my comment shouldn't concern you. But it seems like Docker will throw an error at runtime if the `:shared` option is used in non-Linux environments.
