### ISSUE TITLE
Image not working with rclone union config

### ISSUE THREAD

**Issue by quorn23** [Mumie-hub/docker-services#31]
Hi,

The image works fine on my synology nas with a config for a gdrive mount. 
But if i try to do so with an union mount, it doesn't work.

Config:
`[Series]
type = union
remotes = /volume1/Allseries/dir1 /volume1/Allseries/dir2 /volume1/Allseries/dir3
`
Image creation:
`sudo docker run -d --name rclone-test --restart=unless-stopped --cap-add SYS_ADMIN --device /dev/fuse --security-opt apparmor:unconfined -e RemotePath="Series:"  -e MountCommands="--allow-other --allow-non-empty --dir-cache-time 672h --vfs-cache-max-age 675h --vfs-read-chunk-size 128M --vfs-read-chunk-size-limit 1G --buffer-size 32M" -e ConfigName="rclone.conf" -v /volume1/Docker/rclone:/config -v /volume1/Allseries/dirs:/mnt/mediaefs:shared mumiehub/rclone-mount`

i also tried it with none of the MountCommands, as testing it on a raspi with a simple rcloud mount Series: /mnt/dirs/ --read-only works fine

The mount (dirs) remains empty.

Image creation that works fine (for gdrive)
`sudo docker run -d --name rclone-mount --restart=unless-stopped --cap-add SYS_ADMIN --device /dev/fuse --security-opt apparmor:unconfined -e RemotePath="Rcloud:" -e MountCommands="--allow-other --allow-non-empty --dir-cache-time 672h --vfs-cache-max-age 675h --vfs-read-chunk-size 128M --vfs-read-chunk-size-limit 1G --buffer-size 32M" -e ConfigName="rclone.conf" -v /volume1/Docker/rclone:/config -v /volume1/shares/rclone:/mnt/mediaefs:shared mumiehub/rclone-mount`

Edit: When i bash into the image /mnt/mediaefs is empty as well.

**Comment by quorn23** [comment]
`/config # rclone mount Series: /mnt/mediaefs/
2019/07/05 00:01:55 NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults
2019/07/05 00:01:55 Failed to create file system for "Series:": didn't find section in config file
/config #`
If i trying to mount directly in the container. I do see the /config directory and with less rclone.conf i see that it indeed mounted my config file

**Comment by animosity22** [comment]
Looks more like a docker issue rather than rclone.

**Comment by quorn23** [comment]
Error on my part, i never told docker the volumes to work with, obvl Docker needs to know.
