### ISSUE TITLE
Mounting multiple drives 

### ISSUE THREAD

**Issue by Lonli-Lokli** [Mumie-hub/docker-services#36]
Hi!

Currently Im using multiple drives (even multiple shared GDrives as well) and it would be good to have an ability to mount all of them inside docker to make them available

**Comment by Nornode** [comment]
Hey Lonli-Lookli, 
Just use multiple replicas of the same container with a bit different configurations instead. 
It's a preferred model that one container has one purpose.

**Comment by Mumie-hub** [comment]
@Lonli-Lokli the preferred way would be to start multiple container for every mount. or use a docker-compose file like in the example and just `docker-compose up -d`
