### ISSUE TITLE
Rclone-mount config location

### ISSUE THREAD

**Issue by NDuggan** [Mumie-hub/docker-services#39]
@Mumie-hub  For some unknown reason when I launch the container `rclone` doesn't appear to be looking in the correct config location.

```sh
$ docker-compose exec rclone-mount sh
$ rclone config file
Configuration file doesn't exist, but rclone will use this path:
/root/.config/rclone/rclone.conf
```
I can get it to work by mounting (twice), once into the location specified in the docs and once into the aforementioned location. If I do this everything works perfectly.

```Dockerfile
---
version: "3"
services:
  rclone-mount:
    image: mumiehub/rclone-mount
    container_name: rclone-mount
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    environment:
      - RemotePath=gcrypt:
      - MountCommands=--allow-other --allow-non-empty
    volumes:
      - /root/.config/rclone:/root/.config/rclone
      - /root/.config/rclone:/config
      # - /root/.config/rclone/rclone.conf:/config/.rclone.conf # ALSO TRIED THIS
      - /mnt/gdrive:/mnt/mediaefs:shared
    restart: unless-stopped
```

Am I doing something wrong or is this a bug caused by an upstream change?

**Comment by NDuggan** [comment]
I don't know if this was something cached locally, but I tried it multiple times without no luck. And then finally it just worked (with the suggested mount points).

Closing for now, sorry! 👍

**Comment by NDuggan** [comment]
@Mumie-hub OK, I think the success earlier was a false positive as I saw the following logs:

```log
rclone-mount    | [cont-init.d] 20-init: exited 0.
rclone-mount    | [cont-init.d] 30-check: executing...
rclone-mount    | [cont-init.d] 30-check: MountPoint /mnt/mediaefs is ready
rclone-mount    | [cont-init.d] 30-check: exited 0.
rclone-mount    | [cont-init.d] done.
rclone-mount    | [services.d] starting services
rclone-mount    | [services.d] [rclone-mount]-run: starting rclone mount 2020.03.26-21:18:28
rclone-mount    | [services.d] done.
```

But when running I still it was like `rclone` still wasn't loading the correct config (so I'm back to mounting twice so it will work):

```sh
$ docker-compose exec rclone-mount rclone config file
Configuration file doesn't exist, but rclone will use this path:
/root/.config/rclone/rclone.conf
```

**Comment by Mumie-hub** [comment]
I think you are mixing something up.
the standard `.rclone.conf` is invisible. When you just mount the folders, you can specify the filename with `ConfigName` and in your case it must be `rclone.conf` without dot at the beginning of the filename:
```
version: "3"
services:
  rclone-mount:
    volumes:
      - /root/.config/rclone:/config
    environment:
      ConfigName: "rclone.conf"
```

- /root/.config/rclone:/config

**Comment by NDuggan** [comment]
Thanks for the reply.

The default is `rclone.conf` in newer versions of Rclone. But following the instructions on Docker Hub I ended up trying both the hidden and normal file versions; I even tried mounting a folder with both versions in, but the problem seemed to be that the location was incorrect altogether (as opposed to the file name).

I didn’t change the `ConfigName` as I was trying to stick to the defaults, but am happy to do so if that’s the suggested approach.

I’m currently just mounting directly on the host system using the standard rclone mount command, as docker-compose deprecated the `volumes_from` option, which means the only thing I gain from mounting in a container is to have it run like a systemd service (unless I’m missing something, please correct me if I’m wrong).

As a side note, when bringing the container up it would randomly hang during the fetch/install of APK system updates. But stopping and starting or recreating it would just bring it straight back up without any delay.

**Comment by Mumie-hub** [comment]
running rclone as a systemd service is totally fine too. The default config path inside the container is 
`/config/.rclone.conf` ( can't change the default here, because it maybe breaks some mountcommands from other users ). What do you mean by hanging at the apk update step, hanging forever? Maybe a problem with the DNS of the hostsystem?!

**Comment by NDuggan** [comment]
@Mumie-hub that all makes sense, wasn't saying it should be changed, just pointing out that it was different and that maybe that's what was causing my problems.

The apk update just hangs forever (sometimes). Doesn't appear to be a host issue as whilst it's hanging I can fetch the contents of the URL manually. Weirdly I can also ping the endpoint from the container which is hanging. And to make matters worse if I just try it again, it will work…

Don't worry about it too much if no one else is complaining. I'm currently using a systemd service as it fits my needs. The container would have been nice to contain everything within Docker (compose), but it's not a major overhead. Maybe it makes more sense to mount the drive before Docker startup anyway?
