### ISSUE TITLE
Container states that rclone process doesn't exist, keeps restarting

### ISSUE THREAD

**Issue by rammellzee** [Mumie-hub/docker-services#43]
I've used this container for months and I've had no issues, the container was working a few days ago (I believe since last week) but I noticed today that it no longer works. When I check the logs it repeats this error message:     
   
> [services.d] [rclone-mount]-finish: rclone process not present, restarting container[ERROR]  
     
The container then exits and restarts, it continually does this but nothing new happens. I've tried recreating the container as well as deleting the image and downloading it again. Those steps didn't work, the container is still broken. Any ideas on how to fix the issue?

**Comment by Mumie-hub** [comment]
I tested and also rebuild the container. Its working fine. Can you show your docker run command?
Best Regards

**Comment by rammellzee** [comment]
Sorry, this turned out to be my own error with my exclude file containing characters that were spitting out errors. I have changed the file and the container works great just like it used to.
