### ISSUE TITLE
Multiple remote mounts with single container.

### ISSUE THREAD

**Issue by bachulator** [Mumie-hub/docker-services#53]
Hi @Mumie-hub.

Just wondering is it possible to mount multiple  remotes with single container instance. If not perhaps redefining the "RemotePath "and "MountPoint" to arrays, And the going one by one in mounting procedure could be a easy fix. Force to run multiple containers to serve multiple cloud services  which feels bit a waist of resources. Great implementation otherwise. Thanks.

**Comment by LeidenSpain** [comment]
Hi,

I just came in to ask the same question
I would like to have different drives in the same mount point (all in /mnt/)
/mnt/GDrive
/mnt/OneDrive
/mnt/Box
/mnt/DropBox

**Comment by Mumie-hub** [comment]
I would definitely use multiple containers (one process per container). It does not use more resources (one rclone process on the host in its own namespace for each fuse mount). With a single container, s6 would have to start a process/service for each remote (possible for sure, but separated in individual containers is better i think). It is also no Problem to mount like @LeidenSpain mentioned.

**Comment by LeidenSpain** [comment]
ok well I'll do it that way
Greetings and thanks
