### ISSUE TITLE
rclone-mount containers always growing

### ISSUE THREAD

**Issue by greenmansuperhero** [Mumie-hub/docker-services#61]
Hi,
after a while, especially when transferring big files, the container grows and disk data is never released.
This caused the container to eat up all disk space in the system drive (docker), with some issues following.
Seems not related to rclone cache, as even if setting up a cachedir the growth is steady anyway.
Recreating the container wipes out everything (obviously). 

Cheers

**Comment by Mumie-hub** [comment]
Can you execute something like `du -h .` inside the container. Did you limit the cache size (something like --vfs-cache-max-size)? When there is no cache limit, the cache is growing indefinitely i assume.

**Comment by greenmansuperhero** [comment]
The problem was related to long running  rsync job that were filling up the
cache.
I've split the jobs in multiple chunks and now situation is resolved. Not
sure how to replicate again the issue.
