### ISSUE TITLE
rclone-mount image contains unnecessary files which takes too much space

### ISSUE THREAD

**Issue by zzjjbb** [Mumie-hub/docker-services#64]
In the dockerfile, it copies the whole `rclone` folder from the builder to `/usr/local/sbin` of the final image. This folder contains many unnecessary files, including an 170+MB `.git` folder. These unnecessary files occupy over 2/3 of the size of the image. I suggest only copying the binary file as this pull request: #63 

Besides, the compiled binary file is much larger than the pre-compiled binary file from https://rclone.org/downloads/ . Is it a good idea to directly download it rather than compile it manually again?

**Comment by Mumie-hub** [comment]
You are totally right. I never recognized that. I fixed that in der Dockerfile and also added fuse3 package for the latest clone version.
