### ISSUE TITLE
filebot.conf file always replaced at container startup

### ISSUE THREAD

**Issue by flo313** [Mumie-hub/docker-services#9]
Hello,

First of all thanks for this amazing work! This container exactly correspond to my need.

I find that the filebot.conf file is always replaced at container startup. The start.sh script refer to a bad path when checking conf file (line 8):
      if [ ! -f $CONFIG_FILE/filebot.conf ]
should be better like this
      if [ ! -f **$CONFIG_DIR**/filebot.conf ] or if [ ! -f **$CONFIG_FILE** ]

Regards
Flo313

**Comment by Mumie-hub** [comment]
I fixed the Error #10  . Iam not using Filebot anymore, so i cant tell if there are other failures.
Best Regards
